import dotenv from "dotenv";
dotenv.config();
const varEnv = {
  PORT: process.env.PORT,
  MONGO_URI: process.env.MONGO_URI,
  NODE_ENV: process.env.NODE_ENV,
  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
  JWT_ACCESS_EXPIRES: process.env.JWT_ACCESS_EXPIRES,
  REFRESH_TOKEN_EXPIRE: process.env.REFRESH_TOKEN_EXPIRE,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  BCRYPT_SALT_ROUND: process.env.BCRYPT_SALT_ROUND,
  SUPER_ADMIN_EMAIL: process.env.SUPER_ADMIN_EMAIL,
  SUPER_ADMIN_PASSWORD: process.env.SUPER_ADMIN_PASSWORD,
  EXPRESS_SESSION_SECRET: process.env.EXPRESS_SESSION_SECRET,
  GOOGLE_CALLBACK: process.env.GOOGLE_CALLBACK,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  FRONTEND_URL: process.env.FRONTEND_URL,
  SSL: {
    SSL_STORE_ID: process.env.SSL_STORE_ID,
    SSL_STORE_PASS: process.env.SSL_STORE_PASS,
    SSL_PAYMENT_API: process.env.SSL_PAYMENT_API,
    SSL_VALIDATION_API: process.env.SSL_VALIDATION_API,
    SSL_SUCCESS_URL_BACKEND: process.env.SSL_SUCCESS_URL_BACKEND,
    SSL_FAIL_URL_BACKEND: process.env.SSL_FAIL_URL_BACKEND,
    SSL_CANCEL_URL_BACKEND: process.env.SSL_CANCEL_URL_BACKEND,
    SSL_SUCCESS_URL_FRONTEND: process.env.SSL_SUCCESS_URL_FRONTEND,
    SSL_FAIL_URL_FRONTEND: process.env.SSL_FAIL_URL_FRONTEND,
    SSL_CANCEL_URL_FRONTEND: process.env.SSL_CANCEL_URL_FRONTEND,
  },
};
export default varEnv;
